name = "ga-analytics-worker"
main = "src/index.js"
compatibility_date = "2025-02-17"

[[unsafe.bindings]]
name = "API_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 30, period = 60 }

[observability.logs]
enabled = true