name = "lastfm-worker"
main = "src/index.js"
compatibility_date = "2024-02-19"

[[unsafe.bindings]]
name = "API_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 60, period = 60 }

[vars]
LASTFM_USERNAME = "megaturtl"

[observability.logs]
enabled = true